FROM python:3.12-slim AS stage0

WORKDIR /app

COPY . .

RUN python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.12-slim

WORKDIR /app

COPY --from=stage0 /opt/venv /opt/venv
COPY --from=stage0 /app /app

ENV PATH="/opt/venv/bin:$PATH"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
